### ISSUE TITLE
CSP policy leads to "Wasm code generation disallowed in this context" errors

### ISSUE THREAD

**Issue by saivann** [nodeca/pica#108]
Websites implementing a secure CSP policy such as the one below can't use the library.
```
base-uri 'self'; object-src 'none'; script-src 'unsafe-inline' 'nonce-" + cspPolicy.nonce + "' 'strict-dynamic' 'self'
```

They instead get a `Wasm code generation disallowed in this context` error.
![capture du 2017-10-12 18-02-58](https://user-images.githubusercontent.com/3578089/31521706-84a6a564-af78-11e7-9a77-f9723815d1c1.png)

It appears that Chrome treats Wasm the same way a eval:
https://bugs.chromium.org/p/chromium/issues/detail?id=686369

The library states that Wasm is optional. Any chance the library can do feature-testing here to see if Wasm is functional before attempting to use it?

**Comment by puzrin** [comment]
Thanks for info. I'll try to fix.

**Comment by puzrin** [comment]
Please check v4.0.1 and let me know if error fixed or no

**Comment by puzrin** [comment]
Some insight:

- Pica uses [multimath](https://github.com/nodeca/multimath) to manage wa/js implementations.
- Multimath has possibility of lazy init, but methods pinning is not lazy (happens immediately in `.use()`, because we rely on sync WA detection).
- I had 2 ways to fix:
  - pin methods in lazy way on first call, detect errors & repin fallbacks (more complex)
  - try to execute small WA module in detector https://github.com/nodeca/multimath/blob/master/lib/wa_detect.js

I used more simple way. In theory it can fail, but i can't imagine such situation. If you still have error, let me know and i will do more robust implementation.

**Comment by saivann** [comment]
Thank you so much! Yes I can confirm 4.0.1 fixes the issue.

That was a fantastically quick fix :)
