### ISSUE TITLE
Asking suggestion on how to improve the resize webgl shader

### ISSUE THREAD

**Issue by asturur** [nodeca/pica#114]
Hello everyone,
i m a developer of fabricjs, a general purpose canvas library.
No issue here, i m just asking for suggestions.

I was trying to write a webgl lanczos resize filter and since i use pica on web browsers for my works, i decided to come here for inspiration, and i saw you ditched away the webgl shader when switched to pica 3.

At the end i managed to put up a shader that works good and i made a demo here
http://fabricjs.com/lanczos-webgl

on the right of the canvas where you find the resizable image, there is the filter information, number of taps and constants.
When scale goes down, number of taps grows up, and that is normal, up to 80 ( i limited the scale factor but goes easily up and up ) at that point of course things become to be slow ( 80 symmetric on the 0 point is 161 pixel for each pixel resized ).

I was wondering if i can subsample in some clean way that taps so that i can keep using a fixed amount of taps ( up to 30 maybe ) but instead of taking one near the other i would take them more sparse.

Do you think is a possible optimization?

this is the shader i generate each time.
uDelta is either   1,0 or 0,1 to indicate horizontal or vertical pass, while uTaps are the constants for the filter, calculated by cpu each pass ( vertical and horizontal )
```glsl
precision highp float;
uniform sampler2D uTexture;
uniform vec2 uDelta;
varying vec2 vTexCoord;
uniform float uTaps[11];
void main() {
  vec4 color = texture2D(uTexture, vTexCoord);
  float sum = 1.0;
  color += texture2D(uTexture, vTexCoord + 1.0 * uDelta) * uTaps[0];
  color += texture2D(uTexture, vTexCoord - 1.0 * uDelta) * uTaps[0];
  sum += 2.0 * uTaps[0];
  color += texture2D(uTexture, vTexCoord + 2.0 * uDelta) * uTaps[1];
  color += texture2D(uTexture, vTexCoord - 2.0 * uDelta) * uTaps[1];
  sum += 2.0 * uTaps[1];
  color += texture2D(uTexture, vTexCoord + 3.0 * uDelta) * uTaps[2];
  color += texture2D(uTexture, vTexCoord - 3.0 * uDelta) * uTaps[2];
  sum += 2.0 * uTaps[2];
  color += texture2D(uTexture, vTexCoord + 4.0 * uDelta) * uTaps[3];
  color += texture2D(uTexture, vTexCoord - 4.0 * uDelta) * uTaps[3];
  sum += 2.0 * uTaps[3];
  color += texture2D(uTexture, vTexCoord + 5.0 * uDelta) * uTaps[4];
  color += texture2D(uTexture, vTexCoord - 5.0 * uDelta) * uTaps[4];
  sum += 2.0 * uTaps[4];
  color += texture2D(uTexture, vTexCoord + 6.0 * uDelta) * uTaps[5];
  color += texture2D(uTexture, vTexCoord - 6.0 * uDelta) * uTaps[5];
  sum += 2.0 * uTaps[5];
  color += texture2D(uTexture, vTexCoord + 7.0 * uDelta) * uTaps[6];
  color += texture2D(uTexture, vTexCoord - 7.0 * uDelta) * uTaps[6];
  sum += 2.0 * uTaps[6];
  color += texture2D(uTexture, vTexCoord + 8.0 * uDelta) * uTaps[7];
  color += texture2D(uTexture, vTexCoord - 8.0 * uDelta) * uTaps[7];
  sum += 2.0 * uTaps[7];
  color += texture2D(uTexture, vTexCoord + 9.0 * uDelta) * uTaps[8];
  color += texture2D(uTexture, vTexCoord - 9.0 * uDelta) * uTaps[8];
  sum += 2.0 * uTaps[8];
  color += texture2D(uTexture, vTexCoord + 10.0 * uDelta) * uTaps[9];
  color += texture2D(uTexture, vTexCoord - 10.0 * uDelta) * uTaps[9];
  sum += 2.0 * uTaps[9];
  color += texture2D(uTexture, vTexCoord + 11.0 * uDelta) * uTaps[10];
  color += texture2D(uTexture, vTexCoord - 11.0 * uDelta) * uTaps[10];
  sum += 2.0 * uTaps[10];
  gl_FragColor = color / sum;
}
```

**Comment by puzrin** [comment]
1. AFAIK, number of operations depends on input size, but does not depends too much on output size.
2. Try to dig `libvips` sources. They use fast pre-sampling for big scale ratios. Don't know anything result quality.

Also note, we dropped shaders because could not achieve binary equal results with JS. That's not acceptable in our case.

**Comment by asturur** [comment]
I noticed that number of operation per pixel to scale depends on scale ratio.
Of course the bigger the image the bigger the number of pixel to pull down.

As far i can tell there is no way to equal webgl with JS math in anyway, due to different precisions when multiplying between the 2. I m not really concerned about that but i understand your point.

I ll look at libvips thanks!

**Comment by puzrin** [comment]
Note, that libvips algo (with pre-downscale) has no quality researches/measurements. If you use well-investigated math - users understand what to expect. In other case that will be a black box.

As example - libvips provided quality below average, before i pointed to this problem. Now they switched to lanzos3 with prescale, but i still has no idea how correct that prescale is (to be honest, i have many doubts about corectness). If you have a time - try to reach Nicolas Robidoux, he did math for ImageMagick.

**Comment by asturur** [comment]
i was just thinking to decimate my taps.
I'm not interested in mathematical correctness. Just nice looking results. I'm fine to remove the lanczos name from the filter if i deviate from the right formula.

for example instead of sampling 80pixels left and 80 pixels right when downscaling, i can sample 40, jumping each other pixel.

or maybe i can just scale max 50% at time.

**Comment by puzrin** [comment]
If your goal is screen-only "nice looking" image with fast render, then libvips approach will be good for you, IMHO. They do:

- "mipmapping" to 1..2 : 1 ratio (probably, with some loss on edges)
- pre-blur with small radius (can be calculated "straight", not as in `glur`, because radius < 1)
- lanczos3 final downscale

That's a principle, but it's better to look details in sources.

My subjective quality criteria is "much worse than pica" / "like pica or better" :) . IMHO, libvips results are "good enougth".

**Comment by asturur** [comment]
well is screen only since yes.
If i serve a result to a user where i need to downscale images for download/print i use pica since i have time to render it and i know it will not fail me.

If i m resizing on the fly as in the demo, an approximated lanczos is good enough i think.

That filter in the library is not meant to replace a real good resizer, just to make you work with something that are not random pixels on the screen from a lazy canvas resize.

**Comment by puzrin** [comment]
In theory, this approach should work when you need to downscale huge image to small thumbnail (will be binary equal with high probability):

- reduce to 3:1..2:1 with linear resize (win=1). 3x time falter than lanczos3 (libvips use integer ratio downscale - much faster, but can eat last pixels in row/column if i understand right).
- apply true lanczos3 to the rest
- unsharp mask if needed

But i had no motivation to experiment :)

Also note:

- The most expensive may be not math, but jpeg extract + getPixels/putPixels + jpeg compress. Seriously.
- Problem with webgl is that image can be out of video memory limits. And if you try to slice, that will be very slow because textures load is expencive. May be webgl2 should help here.

**Comment by asturur** [comment]
well expensive or not, once the texture is up and cached, i get sub 1ms timing with chrome for normal resizes ( under 20 taps ).
Webgl has problems, but for apps that do filtering preview and many filtering is a huge speedup.
It change from unusable to smooth.

i can take this approach i like it. I resize with 1 lobe to half if the ratio is lesser than 25%, then i finish with lanczos 3. i should experiment better.
