### ISSUE TITLE
WebGL? Anyone?

### ISSUE THREAD

**Issue by puzrin** [nodeca/pica#12]
Does anyone wish to make WebGL resize implementation? I don't know if WebGL allows to work with images of any size and is it technically possible to solve this task. But convolver should be extremely fast there.

PS. I'm far from this area, and will not find time to dig it.

**Comment by DevotionGeo** [comment]
Is pica supported on all the browsers which support html5 canvas element ?

**Comment by puzrin** [comment]
WebGL support landed to master. Demo updated. Everybody encouraged to test on different devices, see instructions in readme.

**Comment by gezilinll** [comment]
I have implemented a GPU version of Pica which is high quailty image resizer.

🔗 GitHub Repo: https://github.com/gezilinll/pica-gpu

🔗 Demo: https://pica-gpu.gezilinll.com/

The GPU version of Pica achieves the same anti-moiré effect and sharpness as the original Pica while improving performance by 2-10×, with greater speedup for larger images. Additionally, because the GPU implementation avoids creating extra buffers, memory usage is lower. CPU load is also significantly reduced, which should help prevent performance bottlenecks.
