### ISSUE TITLE
Possible brighness change on resize

### ISSUE THREAD

**Issue by puzrin** [nodeca/pica#21]
After #20 

I don't know is it correct or not, but should resize keep brightness "energy" intact? Simple check - resize white box. Should resize be exactly white (FFFFFF) or can be FEFEFE?

Need to recheck filter weights and rounding 14 bit <-> 8 bit everywhere.

**Comment by dene-** [comment]
Don't worry, now it does work perfectly! It should be exactly white and now it come up totally white. Probably the problem was also mine, cause I reuploaded portions of the image to imgur... and that probably changed the white, maybe a bit. But now really works well! It would need the unsharp mask fixes now? Although I never had any!

**Comment by puzrin** [comment]
So, is it white without changes i suggested or only after those changes?

**Comment by dene-** [comment]
It was a change after the fix, I could notice it after uploading a picture on Instagram. And now there's any issue after adding the fix in the convolvers, so yeah, after the changes is totally fixed.

**Comment by puzrin** [comment]
Ok, then this ticket is valid, and i need to check is math good enougth to apply for mainstream.

**Comment by avalanche1** [comment]
Hey!
I've just noticed that reduction in brightness. Will try out your suggested fix, but it'd be nice to see it fixed in main repo.
