### ISSUE TITLE
webworkify library used

### ISSUE THREAD

**Issue by FarSeeing** [nodeca/pica#222]
Hey there.

There's an issue with `webworkify` library used when bundling with webpack: since now webpack uses arrow functions for modules (honestly, don't know when that happened) and the library uses [`arguments`](https://github.com/browserify/webworkify/blob/master/index.js#L1) you will have an error.

I understand that's not a problem with `pica` but since `webworkify` was last updated on 2017 and doesn't seem to be in development anymore - maybe it's worth replacing it with something else?

Thanks.

**Comment by puzrin** [comment]
1. There are still no good replacement for webworkify.
2. https://github.com/nodeca/pica/blob/master/package.json#L12. You probably do something wrong, because pica uses prebuild & transpiled files.
3. Some known issues may be related to terser options https://github.com/nodeca/image-blob-reduce#known-issues, just disable those.
