### ISSUE TITLE
Please add typescript definition for this lib

### ISSUE THREAD

**Issue by sciu** [nodeca/pica#63]
I think it would be nice to add support for typescript and also docs to use this lib with Ionic2.
Thanks.

**Comment by puzrin** [comment]
No ideas what is typescript and why it's support should be here.

**Comment by ezequielzacca** [comment]
that doesnt seem the appropiate way of answering the issue, specially since typescript is so popular, if you dont know what typescript is you can go and read about it. Very unprofessional response

**Comment by TheCelavi** [comment]
Buahahahahhahahahahahahahhahahaha

"that doesnt seem the appropiate way of answering the issue, specially since typescript is so popular, if you dont know what typescript is you can go and read about it. Very unprofessional response"

@ezequielzacca This is OS project, under MIT license, if you thing that something is missing, make u f**** PR - contribute, you lazy leech! Shame on you! 

@puzrin I need TS typings as well - seams that you do not have those, so, ok, when I am done, I will send them to you - if you are willing to include it to your project. 

In general, it is just one file, exposing API of your lib to users which are using TypeScript, not vanilla JS. (typescript is JS subset, it gets compiled to JS).

**Comment by puzrin** [comment]
@TheCelavi that can be difficult to maintain. AFAIK there are https://github.com/DefinitelyTyped/DefinitelyTyped, and definitions can be typed/maintained independently.
